[package]
name = "decky_plugin"
version = "0.1.0"
edition = "2021"
authors = ["Christopher-Robin Ebbinghaus <git@cebbinghaus.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usdpl-back = { version = "0.9" }

# logging
log = "0.4"
simplelog = "0.12"

tokio-udev = "0.8.0"
serde_json = "1.0"
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.26"
steam-acf = "0.1.0"
keyvalues-serde = "0.1.0"
serde = { version = "1.0.0", features = ["derive", "rc"] }
surrealdb = { version = "^1.0.0-beta.8", default-features = false, features = ["kv-mem", "kv-rocksdb"]}

[features]
default = []
encrypt = ["usdpl-back/encrypt"]
decky = ["usdpl-back/decky"]

[profile.release]
debug = false
strip = true
lto = true
codegen-units = 4
