[package]
name = "backend"
version = "0.9.5"
edition = "2021"
license = "GPL-2.0"
authors = ["Christopher-Robin Ebbinghaus <git@cebbinghaus.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
log = "0.4"
simplelog = "0.12"
once_cell = "1.18.0"
chrono = "0.4.24"
serde_json = "1.0"
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.26"
keyvalues-serde = "0.1.0" # Key Value format that Steam uses
async-trait = "0.1.68"
serde = { version = "1.0.145", features = ["derive", "rc"] }
slotmap = { version = "1.0.6", features = ["serde"] }
glob = "0.3.1"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
debug = false
strip = true
lto = true
codegen-units = 4

[profile.docker]
inherits = "release"
debug = false
strip = true
lto = "thin"
codegen-units = 16
opt-level = 2
debug-assertions = false
overflow-checks = false
